# Generated by Django 4.0.5 on 2022-06-25 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report_saver', '0002_alter_file_name_alter_file_template_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='template_id',
            new_name='template_name',
        ),
        migrations.RemoveField(
            model_name='file',
            name='created_time',
        ),
        migrations.RemoveField(
            model_name='file',
            name='updated_time',
        ),
    ]
