# Generated by Django 4.0.5 on 2022-06-26 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_saver', '0003_rename_template_id_file_template_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='encrypt_key_id',
            new_name='encrypt_key',
        ),
        migrations.RenameField(
            model_name='file',
            old_name='optimal_store_point_id',
            new_name='optimal_store_point',
        ),
        migrations.RenameField(
            model_name='file',
            old_name='template_name',
            new_name='template_id',
        ),
        migrations.AddField(
            model_name='file',
            name='compression_algo',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
