version: '3'

services:
  minio-oci:
    image: minio/minio:latest
    container_name: minio-oci
    hostname: minio-oci
    # restart: always
    networks:
      file_server_net:
        ipv4_address: 172.20.0.10
    ports:
      - '9010:9000'
      - '9011:9001'
    environment:
      - MINIO_ACCESS_KEY=12345678
      - MINIO_SECRET_KEY=password
      - CONSOLE_ACCESS_KEY=test
      - CONSOLE_SECRET_KEY=test
    command: server --address ":9000" --console-address ":9001" /data
    volumes:
      - ./minio_data_oci:/data
  
  minio-azure:
    image: minio/minio:latest
    container_name: minio-azure
    hostname: minio-azure
    networks:
      file_server_net:
         ipv4_address: 172.20.0.11
    # restart: always
    ports:
      - '9020:9000'
      - '9021:9001'
    environment:
      - MINIO_ACCESS_KEY=12345678
      - MINIO_SECRET_KEY=password
      - CONSOLE_ACCESS_KEY=test
      - CONSOLE_SECRET_KEY=test
    command: server --address ":9000" --console-address ":9001" /data
    volumes:
      - ./minio_data_azure:/data
      
networks:
  file_server_net:
    driver: bridge
    external: true
    ipam:
      config:
        - subnet: 172.20.0.0/24
      