# Generated by Django 4.0.5 on 2022-06-25 11:58

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name', models.CharField(default='xxx-template', max_length=255)),
                ('company_name', models.CharField(default='xxx', max_length=255)),
                ('created_time', models.DateTimeField(auto_now=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('encrypt_key', models.CharField(max_length=600, null=True)),
                ('compressing_algo', models.CharField(max_length=255, null=True)),
                ('storage_points', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), null=True, size=None)),
                ('optimal_store_point', models.CharField(max_length=255, null=True)),
                ('file_name_patterns', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=150), null=True, size=None)),
            ],
        ),
    ]
